name: denoiser
channels:
    - conda-forge
    - nvidia
dependencies:
    - python
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tensorflow=2.6
    - torchvision
    - tqdm
    - Pillow
    - tensorflow-gpu
    - cudatoolkit
    - cudnn=8.1
    - pip
    - pip:
        - soundfile
        - torch
        - librosa