name: denoiser
channels:
    - conda-forge
dependencies:
    - python=3.10.11
    - librosa
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tensorflow
    - torchvision
    - tqdm
    - Pillow
    - pip
    - pip:
        - soundfile
        - torch