name: sepctrogram_denoiser
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - pip:
        - librosa
        - matplotlib
        - numpy
        - soundfile
        - torch
        - torchvision
        - Pillow
        - tqdm